### ISSUE TITLE
Information Tableau : Fonctionnement ?

### ISSUE THREAD

**Issue by ubrisson** [ddaleteam/DdaleApp#7]
Pour rendre l'application fonctionnelle, il nous faut **entre autres** : 
- Stocker la cible (en image) quelque part et de stocker une référence (path ? / id ?)
- Stocker les calques quelque part et d'accéder à leur référence (idem)

Vous pensez quoi de cet ordre de  fonctionnement pour le côté _app/information tableau_ :
1. **Scanner** le  QR code et récupération de l'id de l'œuvre
2. 1er **appel API**, récupération de l'objet oeuvre ( et **stockage** quelque part ? )
3. 2e **appel API**, récupération de l'image cible (à l'aide de l'url trouvée dans l'objet oeuvre)
4. **Stocker** l'image cible quelque part (Assets ? Cache ?) et la référence (dans l'objet œuvre? )
5. Xe **appel API**, récupérer les calques de l'oeuvre (un par un ? dans l'ordre ? en une fois ?)
6. **Stocker** les calques quelque part (res/drawable ? Cache ?) et les refs (dans les Calques de l'œuvre ? )
7. **Lancer** AR activity en transmettant l'œuvre cible ? 
           (avec AR activity ( et AR manager ) qui gèrent le reste avec l'objet œuvre ? )

**Comment by eve-le-guillou** [comment]
Je pense que ce serait mieux de faire ceci : 

 1.   Scanner le QR code et récupération de l'id de l'œuvre
 2.   Lancer AR activity en transmettant l'id de l'oeuvre cible 
 3.   1er appel API, récupération de l'objet oeuvre ( et stockage en tant qu'attribut, comme présentement fait dans QRActivity )
 4.   Récupérer l'image cible à partir de l'URL et la stocker quelque part (Assets ? Cache ?) et les refs
 5.   Récupérer les calques de l'oeuvre à partir des URL en une fois 
 6.   Stocker les calques quelque part (res/drawable ? Cache ?) et les refs (dans les Calques de l'œuvre ? )

Les objets ne se transmettent pas dans des bundles.
